spring:
  application:
    name: bcnc-challenge-api
  devtools:
    add-properties: false
  profiles:
    active: ${SCOPE_SUFFIX}
  sql:
    init:
      mode: always
      schema-locations: classpath:/migrations/schema.sql
      data-locations: classpath:/migrations/data.sql


app:
  title: bcnc-challenge-api
  description: '@project.description@'
  version: '@project.version@'

server:
  port: 8080
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.

springdoc:
  show-actuator: false
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true

