openapi: 3.0.1
info:
  title: api-name
  description: API description
  version: 1.0.0
servers:
  - url: http://domain-of-your-app.melisystems.com
    description: scope = dev | test
  - url: http://domain-of-your-app.melisystems.com
    description: scope = prod
  - url: https://domain-of-your-app.melioffice.com
    description: Server to call from local machine. scope = dev | test
  - url: http://localhost:8080
    description: Local machine for development purposes
paths:
  /rest/resource:
    get:
      tags:
        - groupOfOperationsName
      summary: Operation summary
      description: Operation description
      operationId: operationIdName
      parameters:
        - name: queryParamOne
          in: query
          required: true
          schema:
            type: string
        - name: queryParamTwo
          in: query
          required: true
          schema:
            type: string
        - name: queryParamThree
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseExampleDTO'
        "400":
          description: Missing parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseExampleDTO'
components:
  schemas:
    ResponseExampleDTO:
      type: object
    ErrorResponseExampleDTO:
      type: object
